### ISSUE TITLE
Tracer doesn't Flush before Close

### ISSUE THREAD

**Issue by joshu-stripe** [lightstep/lightstep-tracer-go#95] opened 2017-07-18 17:16 UTC
Hi there,

I noticed that both the [`CloseTracer` function](https://github.com/lightstep/lightstep-tracer-go/blob/4b474a1c389eb591a4f4c6bcebe6f73d59ebd957/tracer.go#L38) and the [`tracerImpl.Close()` implementation](https://github.com/lightstep/lightstep-tracer-go/blob/4b474a1c389eb591a4f4c6bcebe6f73d59ebd957/tracer.go#L186) mention that the desired behavior is to flush the tracer before closing it, but as far as I can tell, neither of these enforce it.

I’m not sure if it would make sense to add a `FlushLightStepTracer` call to `CloseTracer` or to add a `tracerImpl.Flush()` at the beginning of `tracerImpl.Close()`, but I’m happy to write a pull request with a test for either option that would make sense.

Thanks!

**Comment by tedsuo** [comment] 2017-07-18 19:03
Thanks @joshu-stripe, this is a bug. The issue is that tracer does call `Flush` on `Close`, as part of shutting down the report loop. But it does not wait for flush to finish before closing the connection. We are working on a fix right now, we'll link the PR to this issue so you can review.

**Comment by viruslobster** [comment] 2017-07-19 17:37
@joshu-stripe #96 fixes this if you want to take a look

**Comment by tedsuo** [comment] 2017-10-18 20:55
Closing as this has been fixed.

**Closed by tedsuo** 2017-10-18 20:55 UTC
